---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: grafana
  annotations:
    "openshift.io/display-name": Grafana
    description: Grafana deployment for metric visualization
    iconClass: fa fa-cogs
    tags: "lad, grafana, time-series"
parameters:
  - description: The location of the prometheus image
    name: IMAGE_GRAFANA
    value: grafana/grafana:6.4.2
  - description: Memory Limit Grafana
    name: LIMIT_MEMORY_GRAFANA
    value: 1Gi
  - name: APPLICATION_NAME
    value: lad-grafana

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        deploymentConfig: ${APPLICATION_NAME}
        app: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentConfig: ${APPLICATION_NAME}
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - name: ${APPLICATION_NAME}
              image: ${IMAGE_GRAFANA}
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: '1'
                  memory: ${LIMIT_MEMORY_GRAFANA}
          restartPolicy: Always

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}-service
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - port: 3000
          name: http
      selector:
        app: ${APPLICATION_NAME}

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${APPLICATION_NAME}-route
      labels:
        app: ${APPLICATION_NAME}
    spec:
      to:
        kind: Service
        name: ${APPLICATION_NAME}-service
