---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: elasticsearch-deployment-template
  labels:
    app: log-anomaly-detector
parameters:
  - description: Application name
    value: 'lad-elasticsearch'
    name: APPLICATION_NAME
    required: true
  - description: The location of the elastisearch image
    name: IMAGE_ELASTISEARCH
    value: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
  - name: ES_DISCOVERY_TYPE
    value: "single-node"
    description: Discover type flag for elasticsearch deployment
  - name: LIMIT_CPU
    value: "1"
    description: Limit number of CPUs allocated to the container
  - name: LIMIT_MEM
    value: "2G"
    description: Limit amount of memory allocated to the container

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        deploymentConfig: ${APPLICATION_NAME}
        app: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            deploymentConfig: ${APPLICATION_NAME}
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
                - name: "discovery.type"
                  value: ${ES_DISCOVERY_TYPE}
              name: ${APPLICATION_NAME}
              image: ${IMAGE_ELASTISEARCH}
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: ${LIMIT_CPU}
                  memory: ${LIMIT_MEM}
          restartPolicy: Always

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}-service
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - port: 9200
          name: http
        - port: 9300
          name: es-comm
      selector:
        app: ${APPLICATION_NAME}
