apiVersion: v1
kind: Template

labels:
  application: log-anomaly-demo

metadata:
  name: log-anomaly-demo-job

parameters:
  - description: Application name
    from: "anomaly-[a-z0-9]{4}"
    generate: expression
    name: APPLICATION_NAME
    required: true
  - name: APP_IMAGE_URI
    description: "Name of the application image to be pulled from the registry"
    value: "docker-registry.default.svc:5000/aiops-kubeflow-dev/log-anomaly-detector-app"
    required: true
  - name: APP_IMAGE_TAG
    value: "latest"
    required: true
  - name: LIMIT_CPU
    value: "4"
    description: "Limit number of CPUs allocated to the job"
    required: false
  - name: LIMIT_MEM
    value: "4G"
    description: "Limit amount of memory allocated to the job"
    required: false

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: laddemo
      labels:
        app: ${APPLICATION_NAME}
    spec:
      template:
        metadata:
          name: ${APPLICATION_NAME}
        spec:
          volumes:
            - name: lad-demo-volume
              persistentVolumeClaim:
                claimName: lad-demo-log
            - configMap:
                defaultMode: 420
                name: sap-demo
              name: volume-jobconfigmap
          containers:
            - name: ${APPLICATION_NAME}
              image: ${APP_IMAGE_URI}:${APP_IMAGE_TAG}
              command: ["python"]
              args: ["app.py", "run", "--config-yaml", "openshift/.env_config.yaml", "--single-run", "True"]
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 500Mi
                limits:
                  memory: ${LIMIT_MEM}
                  cpu: ${LIMIT_CPU}
              volumeMounts:
                - mountPath: /opt/app-root/src/validation_data
                  name: lad-demo-volume
                - mountPath: /opt/app-root/src/openshift
                  name: volume-jobconfigmap

          restartPolicy: Never
