apiVersion: v1
kind: Service
metadata:
  name: log-anomaly-detector-f20-svc
spec:
  selector:
    app: log-anomaly-detector-f20
  ports:
    - protocol: TCP
      name: metrics
      port: 8080
      targetPort: 8080
