---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: log-anomaly-detector-factstore

objects:

  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
        component: factstore
        customer: ${CUSTOMER_ID}
      name: log-anomaly-detector-factstore
    spec:
      lookupPolicy:
        local: true

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: log-anomaly-detector-factstore
      name: anomaly-detector-factstore
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: log-anomaly-detector-factstore:latest
      source:
        git:
          ref: master
          uri: https://github.com/AICoE/log-anomaly-detector.git
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:3.6
            namespace: openshift
        type: Source
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: ConfigChange

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
        component: factstore
        customer: ${CUSTOMER_ID}
      name: log-anomaly-detector-factstore-${CUSTOMER_ID}
    spec:
      replicas: 1
      selector:
        deploymentconfig: log-anomaly-detector-factstore-${CUSTOMER_ID}
      template:
        metadata:
          labels:
            app: log-anomaly-detector-factstore-${CUSTOMER_ID}
            deploymentconfig: log-anomaly-detector-factstore-${CUSTOMER_ID}
        spec:
          containers:
            - args:
                - app.py
                - ui
              command:
                - python
              image: log-anomaly-detector-factstore:latest
              imagePullPolicy: Always
              name: log-anomaly-detector-factstore
              env:
                - name: SQL_CONNECT
                  value: ${SQL_CONNECT}
                - name: CUSTOMER_ID
                  value: ${CUSTOMER_ID}
              resources:
                limits:
                  cpu: 2
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 500Mi
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - log-anomaly-detector-factstore
            from:
              kind: ImageStreamTag
              name: log-anomaly-detector-factstore:latest
          type: ImageChange

  - apiVersion: v1
    kind: Service
    metadata:
      name: log-anomaly-detector-factstore-${CUSTOMER_ID}-svc
      labels:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
    spec:
      selector:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
      ports:
        - port: 5001
          name: http
  - apiVersion: v1
    kind: Service
    metadata:
      name: log-anomaly-detector-factstore-${CUSTOMER_ID}-metrics-svc
      labels:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
    spec:
      selector:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
      ports:
        - port: 8080
          name: metrics

  - apiVersion: v1
    kind: Route
    metadata:
      name: log-anomaly-detector-factstore-${CUSTOMER_ID}-route
      labels:
        app: log-anomaly-detector-factstore-${CUSTOMER_ID}
    spec:
      to:
        kind: Service
        name: log-anomaly-detector-factstore-${CUSTOMER_ID}-svc

parameters:
  - name: SQL_CONNECT
    value: >
      mysql+pymysql://admin:password@$(MYSQL_56_CENTOS7_SERVICE_HOST):$(MYSQL_56_CENTOS7_SERVICE_PORT)/factstore
  - name: CUSTOMER_ID
    value: "placeholder"
