apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: log-anomaly-detector-demo
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: log-anomaly-detector
      name: log-anomaly-detector
    spec:
      lookupPolicy:
        local: true
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: log-anomaly-detector
      name: anomaly-detector
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: log-anomaly-detector:latest
      source:
        git:
          ref: master
          uri: https://github.com/AICoE/log-anomaly-detector.git
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:3.6
            namespace: openshift
        type: Source
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: ConfigChange
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: log-anomaly-detector-${CUSTOMER_ID}
        component: lad-core
        customer: ${CUSTOMER_ID}
      name: log-anomaly-detector-${CUSTOMER_ID}
    spec:
      replicas: 1
      selector:
        deploymentconfig: log-anomaly-detector-${CUSTOMER_ID}
      template:
        metadata:
          labels:
            app: log-anomaly-detector-${CUSTOMER_ID}
            component: lad-core
            customer: ${CUSTOMER_ID}
            deploymentconfig: log-anomaly-detector-${CUSTOMER_ID}
        spec:
          containers:
            - name: log-anomaly-detector
              image: log-anomaly-detector:latest
              command: ["python"]
              args: ["app.py", "run", "--config-yaml", "openshift/.env_config.yaml"]
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
              volumeMounts:
                - mountPath: /opt/app-root/src/openshift
                  name: volume-jobconfigmap
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: "${CONFIG_MAP}"
              name: volume-jobconfigmap

      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - log-anomaly-detector
            from:
              kind: ImageStreamTag
              name: log-anomaly-detector:latest
          type: ImageChange
parameters:
  - name: CMD
    value: "run --config-yaml validation_data/.env_config.yaml"
  - name: CUSTOMER_ID
    value: "placeholder"
  - name: CONFIG_MAP
    value: "sample-config"
